### ISSUE TITLE
Authorization Required?

### ISSUE THREAD

**Issue by cmer** [flz/iaqualink-py#2] opened 2019-07-23 02:26 UTC
Hi,

I am trying to login to my iAqualink through HomeAssistant and the console and somehow, I can't properly authenticate.

I am able to login just fine at `https://support.iaqualink.com/users/sign_in`

but when I load `https://support.iaqualink.com/devices.json`, I get:

`{"status":"401","error":{"error_code":"error_auth_required","message":"Authorization Required","details":"Please provide proper authentication details."}}`

I am able to use the mobile app from my phone and I see my pool just fine at `https://iaqualink.zodiacpoolsystems.com`.

Is there anything in particular I need to make the `support.iqualink.com` host behave?

Thanks

**Comment by flz** [comment] 2019-07-23 05:25
Are you using my [custom component](https://github.com/flz/hass-aqualink) to log on to iaqualink?

There's a support thread at https://community.home-assistant.io/t/jandy-iaqualink-pool-custom-component/105633.

**Comment by cmer** [comment] 2019-07-23 18:46
Yes I did that. What's really odd is that I am able to log in just fine in the browser at `https://support.iaqualink.com/users/sign_in`, but even though I'm logged in, it gives me 401 Authorization Required (note, not authentication required, AUTHORIZATION required)

![CleanShot 2019-07-23 at 14 45 13@2x](https://user-images.githubusercontent.com/412/61738551-93359380-ad58-11e9-9f45-7d6b72261375.png)


It actually looks like something might be wrong with my account, but as I said, I am assuming this library mimics the mobile application, which works perfectly fine for me on iOS, so I'm not quite sure why this wouldn't work.

**Comment by flz** [comment] 2019-07-23 19:18
I actually have no idea what you're doing. What's your set up like? Have you configured configuration.yaml with your username/password? Why are you using your browser? What are you seeing in homeassistant logs?

You can't just open the devices.json page in a browser like that. This URL requires a POST request to be sent (as opposed to GET, which is done when you open a page this way) along with a bunch of data (including session key).

**Comment by cmer** [comment] 2019-08-14 15:36
Ok. I understand I sound like a complete nut job :) Let me explain exactly what I did here.

As far as I'm aware, there are two "official" ways to control my pool. The [mobile application](https://apps.apple.com/ca/app/iaqualink/id443059509), and their web portal (https://iaqualink.zodiacpoolsystems.com). I am able to log in to both and everything works just fine and as expected.

Since I was having issue with this library (through HomeAssistant), I went digging in the source code and noticed that the login url is:

`AQUALINK_LOGIN_URL = "https://support.iaqualink.com/users/sign_in.json"`

Since this looks awfully like a standard Rails app, I removed `.json` from the URL and went to `https://support.iaqualink.com/users/sign_in` in the browser. From there, I am able to "kind of" login properly. My username/password are accepted, I get logged in, but at the same time, I see `401 Authorization Required`. 

I was wondering if this is also what you see on your end when you do the "browser login hack"? I am not sure if my issues are due to something odd going on with my Aqualink account, or if there's a bug in the code.

I hope this makes a bit more sense. Thanks!

**Comment by cmer** [comment] 2019-08-29 13:08
@flz Just bring this back to the top of your inbox in case you missed it. ^^^

**Comment by flz** [comment] 2019-09-08 02:14
> Ok. I understand I sound like a complete nut job :) Let me explain exactly what I did here.
> 
> As far as I'm aware, there are two "official" ways to control my pool. The [mobile application](https://apps.apple.com/ca/app/iaqualink/id443059509), and their web portal (https://iaqualink.zodiacpoolsystems.com). I am able to log in to both and everything works just fine and as expected.

So far so good.

> Since I was having issue with this library (through HomeAssistant), I went digging in the source code and noticed that the login url is:
> 
> `AQUALINK_LOGIN_URL = "https://support.iaqualink.com/users/sign_in.json"`
> 
> Since this looks awfully like a standard Rails app, I removed `.json` from the URL and went to `https://support.iaqualink.com/users/sign_in` in the browser. From there, I am able to "kind of" login properly. My username/password are accepted, I get logged in, but at the same time, I see `401 Authorization Required`.

I do not use this page. I don't know what it does exactly. I use the URL that you mentioned which returns an authorization key which I store and reuse in later requests.

> I was wondering if this is also what you see on your end when you do the "browser login hack"? I am not sure if my issues are due to something odd going on with my Aqualink account, or if there's a bug in the code.

I don't think there's a bug in the code based on what you're describing. I'm not doing any hack, just reproducing the requests that the mobile app would send. I don't think there's anything wrong with your Aqualink account.

I still don't understand what you want to do exactly. If you want to control your pool with HomeAssistant, use the component I mentioned earlier (or wait for a few more HA releases when the aqualink support gets fully merged). If you want to use the API, use the library.

Closing the issue since there's no actual issue.

**Closed by flz** 2019-09-08 02:14 UTC
